name:        gcloud_cl_user_auth
version:     0.0.1
description: Utilities and library for Google cloud command line user credentials
author:      Gary Smith <argentiapparatus@gmail.com>
homepage:    https://github.com/argentiapparatus/gcloud_user_cl_auth.dart
publish_to:  none
environment:
  sdk:             '>=1.8.3 <2.0.0'
dependencies:
  args:            '^0.13.0'
  googleapis_auth: '^0.2.0'
  googleapis:      '^0.28.0'
dev_dependencies:
  test:            '^0.12.0'
executables:
  gcloud_cl_user_auth: 'gcloud_cl_user_auth'

